### PR TITLE
Support recursive error types

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
@burntsushi — if you don't have any qualms about this functionality, I'll go ahead and merge and release.

**Comment by shepmaster** [comment]
Since we will be implementing a trait for a generated struct we weren't previously, this is technically a breaking change.

**Comment by BurntSushi** [comment]
Aye I haven't looked closely at it, but it sounds good from your comments!

**Comment by shepmaster** [comment]
Released in 0.3.0 🎉

**Pull request merged**
