### PR TITLE
Stop automatically treating location as implicit

### LINKED ISSUE #339: Do not automatically treat `location` as implicit data
The error message generated is poor ("struct \`DemoSnafu\` has no field named \`location\`" / "the trait bound \`WhatShouldHaveBeenLocation: GenerateImplicitData\` is not satisfied") and it's unlikely to be a deeply used feature.

### PR DESCRIPTION
**Pull request by shepmaster**
Closes #339

### CODE REVIEW

**Review by Enet4 — APPROVED** [review]
It may feel a bit odd that we need to explicitly mark it as `implicit`, but once it is made clear that the _implicit_ has to do with the properties being implicitly provided upon error generation, that confusion goes away.

As (AIUI) we cannot reliably identify whether the field `location` is indeed of type `snafu::Location`, I agree that we are better off reducing the chances of false positives.

**Comment by shepmaster** [comment]
> cannot reliably identify whether the field `location` is indeed of type

That's correct. Proc macros only have knowledge of the literal source code, not any types or anything fancy.

**Comment by mhnap** [comment]
> Proc macros only have knowledge of the literal source code, not any types or anything fancy.

Seems `thiserror` somehow handles this correctly, as the backtrace field can be named differently than `backtrace` but if it has the `std::backtrace::Backtrace` type it still will be recognized as backtrace (`provide` method will be generated).

Firstly, I wanted to propose making `Location` implicit by default, but after I found this issue :)

**Comment by shepmaster** [comment]
>> Proc macros only have knowledge of the literal source code, not any types or anything fancy.
>
> Seems thiserror somehow handles this correctly

Can you please provide a code example demonstrating what you mean? I stated that the literal source code is all that the macro gets, but it seems like you are saying that is not true. If so, you should be able to write code where the error type has no literal words like "backtrace" and the automatic backtrace behavior still works:

```rust
use std::backtrace::Backtrace as Wubble;

#[derive(Error, Debug)]
pub struct MyError {
    msg: String,
    wubble: Wubble,
}
```

If you provide that, then I can go digging into thiserror to see how it works.

**Comment by mhnap** [comment]
Yes, you're right. It will work if the field name differs from `backtrace` but the field type still needs to contain `Backtrace`. So, it indeed will not work for your example above.
It works for:
```rust
    #[derive(Error, Debug)]
    pub struct MyError {
        msg: String,
        wubble: std::backtrace::Backtrace,
    }
```
or:
```rust
    use std::backtrace::Backtrace as Backtrace;

    #[derive(Error, Debug)]
    pub struct MyError {
        msg: String,
        wubble: Backtrace,
    }
```
Sorry for misleading.

**Pull request merged**
