### PR TITLE
Add top-level documentation on reporting errors

### LINKED ISSUE #464: Mention Report in the top level docs
> i feel like [using `Report`] should be mentioned in the root crate documentation because i never knew that existed

### PR DESCRIPTION
**Pull request by Enet4**
Resolves #464. I'm open to the possibility of shortening the example code.

### CODE REVIEW

**Review by alerque — COMMENTED** [review]
Add a potential consumer of the docs this shows me roughly what i could do but it is not at all apparent from the docs what the result output would be or why i would want to use this over done alternative.

**Comment by Enet4** [comment]
@alerque Please see whether the new version of the documentation explains the situation better. At this point it is a matter of striking a balance between explaining the purpose of this mechanism and not becoming too redundant with the contents in `macro@report` and `Report`.

**Review by alerque — APPROVED** [review]
I think that is *much* better!

**Review by shepmaster — APPROVED** [review]
Looks good! I just squashed the commits and reworded the commit message a bit.

**Pull request merged**
