### PR TITLE
Expose raw backtrace

### PR DESCRIPTION
**Pull request by dmitry-zakablukov**
Good day!

I would like to expose raw backtrace from shim::Backtrace. This is required for custom backtrace formatting.
So I added a `raw()` method for shim::Backtrace struct.

### CODE REVIEW

**Comment by shepmaster** [comment]
This is already provided. You need to use the [`backtraces-impl-backtrace-crate`](https://docs.rs/snafu/0.6.9/snafu/guide/feature_flags/index.html#backtraces-impl-backtrace-crate) feature flag.

**Comment by dmitry-zakablukov** [comment]
> 
> 
> This is already provided. You need to use the [`backtraces-impl-backtrace-crate`](https://docs.rs/snafu/0.6.9/snafu/guide/feature_flags/index.html#backtraces-impl-backtrace-crate) feature flag.

Oh, I see. Then can you please update a backtrace crate to version 0.3.51 or higher? v0.3.51 contains some specific changes I need in my code.

**Comment by shepmaster** [comment]
> update a backtrace crate to version 0.3.51 or higher

SNAFU is compatible with **any** 0.3.x version of backtrace. The specific version used is up to your project.

**Comment by dmitry-zakablukov** [comment]
@shepmaster , thank you for clarification! Indeed, `backtraces-impl-backtrace-crate` feature flag and specific backtrace crate version in my project solved my problem.

**Pull request closed without merging**
