### PR TITLE
Update compiler error text for Rust 1.38

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by CryZe** [comment]
This is a really odd one, I noticed this when rebasing #138 and I don't understand why this got changed. This seems like a worse error message.

**Comment by shepmaster** [comment]
A good point. Ever stranger, I cannot find this text anywhere in the Rust repo to find out why/when it changed!

**Comment by shepmaster** [comment]
Ah, it's been [completely removed recently](https://github.com/rust-lang/rust/commit/79f0d88de860bed2747811cffba177504d3ead8e). This change occurred in rust-lang/rust@84dfb2c4d7570fad03101bf4931000d029ec3419.

**Comment by shepmaster** [comment]
> when rebasing #138

I haven't forgotten about this, I swear! ❤️

**Pull request merged**
