### PR TITLE
Add optional conversion to `backtrace::Backtrace`

### LINKED ISSUE #118: Snafu cannot be used with color_backtrace::print_backtrace
[color-backtrace](https://crates.io/crates/color-backtrace) is a crate for printing colored, expanded backtraces with source context. It offers, among others, a function [print_backtrace](https://docs.rs/color-backtrace/0.2.2/color_backtrace/fn.print_backtrace.html), which takes backtrace::Backtrace as an argument. I wanted to use it with Snafu, however this crate's [backtrace shim](https://docs.rs/snafu/0.4.1/src/snafu/backtrace_shim.rs.html) hides the required type as private.

Would it be possible to somehow expose the inner type to allow usage with color-backtrace?

### PR DESCRIPTION
**Pull request by ArekPiekarz**
This fixes #118

### CODE REVIEW

**Comment by shepmaster** [comment]
One thing I realized is that this might conflict with some future plans to make our `Backtrace` type always available but only "active" when the backtrace feature is enabled (see #113 for some background). Conceptually, it would look like:

```rust
#[cfg(not(feature = "backtraces"))]
struct Backtrace;

#[cfg(feature = "backtraces")]
struct Backtrace(backtrace::Backtrace)
```

The same root problem might occur whenever the standard library gains a backtrace type: there wouldn't be a backtrace crate in play then.

I wonder if it's worth building in some fallibility here. Instead of `AsRef`, what if we used some inherent method that could return an `Option`? It kinda sucks that we wouldn't be able to use a nice trait, but I'm not immediately seeing an alternative.

This commit would be more like:

```rust
impl Backtrace {
    #[cfg(feature = "backtrace-crate")]
    fn as_backtrace(&self) -> Option<&backtrace::Backtrace> { Some(/* ... */) }

    // Potentially also `into_backtrace` in the future if it's useful.
}
```

In the future, we would change it to be `None` when using the standard library backtrace or if the user has disabled backtraces.

What do you think?

**Comment by ArekPiekarz** [comment]
If I understood correctly the future direction, you would like the `as_backtrace()` method to be always available, but return `Some` only when the feature `"backtrace-crate"` is enabled. It sounds reasonable to move the burden of conditional compilation logic away from users' code.

**Comment by shepmaster** [comment]
> you would like the `as_backtrace()` method to be always available

Originally, I was going to disagree with this, but it made me think a bit harder on the problem, so thank you!

Maybe the final end state could be:

- The `backtraces` feature is disabled by default
- SNAFU unconditionally has a `Backtrace` type, encouraging error type authors to include it in their types.
- When the application author enables the `backtraces` feature, the SNAFU `Backtrace` type starts to carry a `backtrace::Backtrace`.
- The `backtrace-crate` feature implies `backtraces` and adds the `AsRef` implementation as shown in this PR. It wouldn't need to return an `Option` because of the requirement on `backtraces`.
- In the future, we could add a `backtrace-std` feature that also implies `backtraces`. It would be incompatible with the `backtrace-crate` feature, but only an application should enable it so this shouldn't be a problem. At that point in time, we could also implement `AsRef` for the standard library `Backtrace` type.


For a library author, they just scatter `Backtrace` in all of their leaf errors (and `backtrace(delegate)` in aggregating errors, for now).

An application author adds `features = [backtraces]` and *optionally* one of `backtrace-crate`, `backtrace-std` (sometime), if they need to access the underlying type.

**Comment by ArekPiekarz** [comment]
I've been trying to think of an example where library would need the underlying backtrace type on its own and couldn't find any sensible.

In case of recoverable errors it would return Result and not fiddle with backtraces by itself. In case of unrecoverable ones, like wrong indexing in a Vec, it should use "panic!" and leave optional installing of custom panic handler to the application.

One not really sensible scenario would be a library internally handling an error from a Result and deciding to print the backtrace with other library (like color-backtrace), but that would be a bad design by taking the control away from the application and including unnecessary dependencies.

A reasonable case could be a "snafu-helper" library that takes the Snafu backtrace and somehow works on it and the inner type, but that should be invoked by the application.

All in all I think your design makes sense.

**Comment by lucab** [comment]
@shepmaster the above looks sane to me, except one point that I am not fully following, here below.

> An application author adds features = [backtraces] and optionally one of backtrace-crate, backtrace-std (sometime)

If an application has `features = [backtraces]` only, **without** any further `backtrace-crate` or `backtrace-std`, what does `as_backtrace(&self) -> Option<X>` in terms of the inner type "X"?

**Comment by shepmaster** [comment]
> what does `as_backtrace(&self) -> Option<X>` in terms of the inner type "X"

That function would only be present when `backtrace-crate` or `backtrace-std` is also enabled; those are optional and conflict with each other.

**Comment by shepmaster** [comment]
Thanks!

**Pull request merged**
