### PR TITLE
Avoid warnings from bare trait objects

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by shepmaster** [comment]
As you can see from the tests, this is not backwards compatible for all the versions of Rust we support. Instead, you’ll need to add `allow` to the appropriate places.

**Comment by Atul9** [comment]
Hi @shepmaster I am new to rust. What is to be specified with `allow` & `unknown_lints`? Can you please guide me?

**Comment by shepmaster** [comment]
Perhaps we could step back for a second — what prompted you to propose this change in the first place? What problem does it solve?

See [How to disable unused code warnings in Rust?](https://stackoverflow.com/q/25877285/155423) for directions on how to disable warnings.

**Comment by Atul9** [comment]
when I ran cago check I got warnings for trait objects without an explicit 'dyn' are deprecated hence I fix the warnings and opened up a PR.
```
➜  snafu git:(master) ✗ cargo check
   Compiling snafu-derive v0.4.1 (/home/atul/rust/projects/snafu/snafu-derive)
warning: trait objects without an explicit `dyn` are deprecated
  --> snafu-derive/src/lib.rs:26:22
   |
26 | type UserInput = Box<quote::ToTokens>;
   |                      ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn quote::ToTokens`
```

**Comment by shepmaster** [comment]
> when I ran cago check

Are you trying to use SNAFU from your project and the warnings are distracting you? They shouldn't prevent anything from working.

Anyway, there are two main things that need to be done:

1. Add `#![allow(bare_trait_objects)]` to the top of src/lib.rs and probably snafu-derive/src/lib.rs
1. Add `#[allow(bare_trait_objects)]` to each usage of a trait object in the code generated by snafu-derive/src/lib.rs

**Comment by Atul9** [comment]
@shepmaster I got point 1, what do I need to run to get code generated for - `in the code generated by snafu-derive`?

**Comment by shepmaster** [comment]
> what do I need to run to get code generated

This involves using `#[derive(Snafu)]` on an error type.

Ideally, the test suites ([1](https://github.com/shepmaster/snafu/tree/master/tests); [2](https://github.com/shepmaster/snafu/tree/master/compatibility-tests)) exercise all of the possible cases, so if building the tests succeeds without warnings, then you will know you've found them all. 

I guess that `Add #![allow(bare_trait_objects)]` also needs to be added to many of the tests in `tests` as well, or maybe those can be fixed to use the `dyn` keyword...

**Comment by Atul9** [comment]
@shepmaster I added `#![allow(bare_trait_objects)]` & updated the PR but the tests for v1_18 fail with the same error which it failed earlier - 
```error: expected one of `!`, `(`, `+`, `,`, `::`, `<`, or `>`, found `quote`
  --> /tmp/cirrus-ci-build/snafu-derive/src/lib.rs:27:26
   |
27 | type UserInput = Box<dyn quote::ToTokens>;
   |                         -^^^^^ unexpected token
   |                         |
   |                         expected one of 7 possible tokens here```
Can you please guide?

**Comment by shepmaster** [comment]
`#![allow(bare_trait_objects)]` *allows* the old style: `Box<Trait>` **instead** of the new style: `Box<dyn Trait>`. Rust 1.18 does not support `dyn Trait`, so the core library code must not use it. The tests (except for the 1.18-specific tests) can all be updated to the new style.

**Comment by Atul9** [comment]
@shepmaster done, I have updated the PR.

**Comment by shepmaster** [comment]
It does not look like all of the relevant locations have been addressed:

- [nightly](https://cirrus-ci.com/task/5729919479316480) (click on primary, minimum versions, and futures)

**Comment by Atul9** [comment]
@shepmaster as you mentioned - `Rust 1.18 does not support dyn Trait, so the core library code must not use it. The tests can all be updated to the new style` hence I didn't add dyn in `src/lib.rs` & `snafu-derive/src/lib.rs`

**Comment by shepmaster** [comment]
To prevent the warnings from occurring when compiling the core library, `#![allow(bare_trait_objects)]` must be added to the roots of the two crates.

**Comment by Atul9** [comment]
@shepmaster done, I have updated the PR by adding `#![allow(bare_trait_objects)]` to prevent the warnings from occuring.

**Comment by shepmaster** [comment]
Thanks for your contribution! I [made some final tweaks](https://github.com/shepmaster/snafu/compare/ef5fa900e9b007aa2f291efc49aa3db30fb77bf3..fe2f81bc47e04bb876dd85d8793e9ca2d3f073e1) and force-pushed to your branch. 

This should be included in our next release.

**Pull request merged**
